import { calculateRetentions, DEFAULT_RETENTION_RULES } from "./retention";
import { DEMO_ACTOR, type HistoryEntry, type Invoice, type MoneyBreakdown } from "./types";

export const DEMO_PDF_SAMPLES = [
  {
    label: "Construcción · materiales",
    detail: "Factura A combinada, receptor y múltiples conceptos",
    fileName: "factura-construccion-andina.pdf",
    url: "/samples/factura-construccion-andina.pdf",
  },
  {
    label: "Arquitectura · proyecto",
    detail: "Campos en orden alternativo y comprobante separado",
    fileName: "factura-arquitectura-urbana.pdf",
    url: "/samples/factura-arquitectura-urbana.pdf",
  },
  {
    label: "Mantenimiento · instalaciones",
    detail: "Etiquetas abreviadas y emisor/receptor explícitos",
    fileName: "factura-mantenimiento-integral.pdf",
    url: "/samples/factura-mantenimiento-integral.pdf",
  },
  {
    label: "Logística · transporte",
    detail: "Factura digital con varios conceptos",
    fileName: "factura-logistica-sur.pdf",
    url: "/samples/factura-logistica-sur.pdf",
  },
] as const;

function demoInvoice(
  invoice: Omit<Invoice, "retentionLines" | "retentionTotal" | "updatedAt">,
): Invoice {
  const retention = calculateRetentions(invoice.amounts, DEFAULT_RETENTION_RULES);
  return {
    ...invoice,
    updatedAt: invoice.createdAt,
    retentionLines: retention.lines,
    retentionTotal: retention.total,
  };
}

const validAmounts = (net: number, vat: number, total: number): MoneyBreakdown => ({
  net,
  vat,
  total,
  currency: "ARS",
});

const validInvoice: Pick<Invoice, "pages" | "validation"> = {
  pages: 1,
  validation: {
    cuitValid: true,
    amountConsistent: true,
    duplicate: false,
    errors: [],
    warnings: [],
  },
};

export const DEMO_INVOICES: Invoice[] = [
  demoInvoice({
    ...validInvoice,
    id: "demo-construccion",
    number: "00001842",
    type: "A",
    pointOfSale: "0004",
    issueDate: "2026-10-06",
    dueDate: "2026-10-21",
    supplier: { name: "Construcciones Andinas S.A.", cuit: "30-71500123-9" },
    amounts: validAmounts(1_250_000, 262_500, 1_512_500),
    status: "pending",
    source: "demo",
    pdfName: "factura-construccion-andina.pdf",
    pdfSize: 2_161,
    pdfUrl: "/samples/factura-construccion-andina.pdf",
    extractedTextPreview: "Factura A · Construcciones Andinas S.A. · materiales para obra",
    createdAt: "2026-10-08T12:10:00.000Z",
  }),
  demoInvoice({
    ...validInvoice,
    id: "demo-arquitectura",
    number: "00000427",
    type: "C",
    pointOfSale: "0016",
    issueDate: "2026-10-04",
    dueDate: "2026-10-19",
    supplier: { name: "Arquitectura Urbana S.R.L.", cuit: "30-71423456-7" },
    amounts: validAmounts(480_000, 0, 480_000),
    status: "approved",
    source: "demo",
    pdfName: "factura-arquitectura-urbana.pdf",
    pdfSize: 2_076,
    pdfUrl: "/samples/factura-arquitectura-urbana.pdf",
    extractedTextPreview: "Factura C · Arquitectura Urbana S.R.L. · anteproyecto ejecutivo",
    createdAt: "2026-10-07T15:30:00.000Z",
  }),
  demoInvoice({
    ...validInvoice,
    id: "demo-mantenimiento",
    number: "00000763",
    type: "A",
    pointOfSale: "0009",
    issueDate: "2026-10-03",
    dueDate: "2026-10-18",
    supplier: { name: "Mantenimiento Integral S.A.", cuit: "30-71654321-4" },
    amounts: validAmounts(360_000, 75_600, 435_600),
    status: "needs_review",
    source: "demo",
    pdfName: "factura-mantenimiento-integral.pdf",
    pdfSize: 2_091,
    pdfUrl: "/samples/factura-mantenimiento-integral.pdf",
    extractedTextPreview: "Factura A · Mantenimiento Integral S.A. · mantenimiento preventivo",
    createdAt: "2026-10-06T11:45:00.000Z",
  }),
  demoInvoice({
    ...validInvoice,
    id: "demo-logistica",
    number: "00004591",
    type: "A",
    pointOfSale: "0007",
    issueDate: "2026-09-27",
    dueDate: "2026-10-12",
    supplier: { name: "Logística Sur S.A.", cuit: "30-69876543-3" },
    amounts: validAmounts(610_000, 128_100, 738_100),
    status: "rejected",
    source: "demo",
    pdfName: "factura-logistica-sur.pdf",
    pdfSize: 2_081,
    pdfUrl: "/samples/factura-logistica-sur.pdf",
    extractedTextPreview: "Factura A · Logística Sur S.A. · transporte y descarga",
    createdAt: "2026-10-05T09:20:00.000Z",
    rejectionReason: "El remito asociado no fue conformado por el responsable de obra.",
  }),
];

export const DEMO_HISTORY: HistoryEntry[] = [
  {
    id: "history-construccion-upload",
    action: "uploaded",
    description: "Factura 0004-00001842 cargada desde PDF en estado Pendiente.",
    timestamp: "2026-10-08T12:10:00.000Z",
    actor: DEMO_ACTOR,
    invoiceId: "demo-construccion",
    invoiceNumber: "0004-00001842",
  },
  {
    id: "history-arquitectura-approved",
    action: "approved",
    description: "Factura 0016-00000427 aprobada por confirmación explícita.",
    timestamp: "2026-10-07T16:05:00.000Z",
    actor: DEMO_ACTOR,
    invoiceId: "demo-arquitectura",
    invoiceNumber: "0016-00000427",
    fromStatus: "needs_review",
    toStatus: "approved",
  },
  {
    id: "history-arquitectura-review",
    action: "review_started",
    description: "Factura 0016-00000427 enviada a revisión administrativa.",
    timestamp: "2026-10-07T15:50:00.000Z",
    actor: DEMO_ACTOR,
    invoiceId: "demo-arquitectura",
    invoiceNumber: "0016-00000427",
    fromStatus: "pending",
    toStatus: "needs_review",
  },
  {
    id: "history-arquitectura-upload",
    action: "uploaded",
    description: "Factura 0016-00000427 cargada desde PDF en estado Pendiente.",
    timestamp: "2026-10-07T15:30:00.000Z",
    actor: DEMO_ACTOR,
    invoiceId: "demo-arquitectura",
    invoiceNumber: "0016-00000427",
  },
  {
    id: "history-mantenimiento-review",
    action: "review_started",
    description: "Factura 0009-00000763 enviada a revisión administrativa.",
    timestamp: "2026-10-06T12:02:00.000Z",
    actor: DEMO_ACTOR,
    invoiceId: "demo-mantenimiento",
    invoiceNumber: "0009-00000763",
    fromStatus: "pending",
    toStatus: "needs_review",
  },
  {
    id: "history-mantenimiento-upload",
    action: "uploaded",
    description: "Factura 0009-00000763 cargada desde PDF en estado Pendiente.",
    timestamp: "2026-10-06T11:45:00.000Z",
    actor: DEMO_ACTOR,
    invoiceId: "demo-mantenimiento",
    invoiceNumber: "0009-00000763",
  },
  {
    id: "history-logistica-rejected",
    action: "rejected",
    description: "Factura 0007-00004591 rechazada. Motivo: El remito asociado no fue conformado por el responsable de obra.",
    timestamp: "2026-10-05T09:42:00.000Z",
    actor: DEMO_ACTOR,
    invoiceId: "demo-logistica",
    invoiceNumber: "0007-00004591",
    reason: "El remito asociado no fue conformado por el responsable de obra.",
    fromStatus: "needs_review",
    toStatus: "rejected",
  },
  {
    id: "history-logistica-review",
    action: "review_started",
    description: "Factura 0007-00004591 enviada a revisión administrativa.",
    timestamp: "2026-10-05T09:31:00.000Z",
    actor: DEMO_ACTOR,
    invoiceId: "demo-logistica",
    invoiceNumber: "0007-00004591",
    fromStatus: "pending",
    toStatus: "needs_review",
  },
  {
    id: "history-logistica-upload",
    action: "uploaded",
    description: "Factura 0007-00004591 cargada desde PDF en estado Pendiente.",
    timestamp: "2026-10-05T09:20:00.000Z",
    actor: DEMO_ACTOR,
    invoiceId: "demo-logistica",
    invoiceNumber: "0007-00004591",
  },
  {
    id: "history-seeded",
    action: "seeded",
    description: "Se prepararon cuatro facturas ficticias de construcción, arquitectura, mantenimiento y logística.",
    timestamp: "2026-10-05T09:00:00.000Z",
    actor: "Sistema de demostración",
  },
];
